# installation python via geerlingguy role
- src: geerlingguy.pip

# installation docker via geerlingguy role
- src: geerlingguy.docker

# installation java via geerlingguy role
- src: geerlingguy.java

# installation git via geerlingguy role
- src: geerlingguy.git
